// src/ui/views/main-panel/index.ts
import htmlContent from './template.html?raw';
import cssContent from './style.css?raw';
import { AIRequestService } from '../../../api';
import { Store } from '../../../store';
import { Logger } from '../../../utils/logger';
import { PageScraper } from '../../../utils/scraper';
import type { ChatMessage } from '../../../types';

// 在内存中维护当前的对话历史
let currentHistory: ChatMessage[] = [];

/**
 * 🌟 核心动能：利用 HTML5 Canvas 纯手工绘制高颜值的赛博解卦分享卡片
 * 具备极佳的兼容性，完美规避 Shadow DOM 的截图死角
 */
const drawAndExportImage = (analysis: string, result: string) => {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const cardWidth = 600;
    const padding = 40;
    const contentWidth = cardWidth - padding * 2;
    const lineHeight = 28;
    const sectionGap = 35;

    // 设置初始字体以便高精度测量文字宽度
    ctx.font = '15px "PingFang SC", "Microsoft YaHei", sans-serif';

    // 智能文本多段落自动换行算法
    const wrapText = (title: string, text: string, maxWidth: number) => {
        const lines: string[] = [title]; // 头部压入标题
        const paragraphs = text.split('\n');

        paragraphs.forEach(p => {
            if (!p.trim()) {
                lines.push('');
                return;
            }
            let line = '';
            for (let i = 0; i < p.length; i++) {
                const testLine = line + p[i];
                const metrics = ctx.measureText(testLine);
                if (metrics.width > maxWidth) {
                    lines.push(line);
                    line = p[i];
                } else {
                    line = testLine;
                }
            }
            lines.push(line);
        });
        return lines;
    };

    // 预计算两段文字的物理换行排版结果
    const analysisLines = wrapText('【推演分析】', analysis, contentWidth);
    const resultLines = wrapText('【断语结果】', result, contentWidth);

    // 动态计算整张卡片的总像素高度
    let currentY = padding + 65; // 预留顶部标题区域高度
    const analysisStartY = currentY;
    currentY += analysisLines.length * lineHeight + sectionGap;

    const resultStartY = currentY;
    // 为结论卡片增加额外的上下内部 Padding 间距高度
    currentY += resultLines.length * lineHeight + 40 + padding;

    canvas.width = cardWidth;
    canvas.height = currentY;

    // --- 🔮 开始渲染高精度的精美视觉样式 ---
    // 1. 背景色：玄学墨黑科技主题
    ctx.fillStyle = '#141416';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    // 2. 双层赛博金/暗夜灰复古装饰线框
    ctx.strokeStyle = '#d4af37'; // 华丽暗金
    ctx.lineWidth = 2;
    ctx.strokeRect(16, 16, canvas.width - 32, canvas.height - 32);

    ctx.strokeStyle = '#2d2d31';
    ctx.lineWidth = 1;
    ctx.strokeRect(22, 22, canvas.width - 44, canvas.height - 44);

    // 3. 渲染主标题
    ctx.fillStyle = '#d4af37';
    ctx.font = 'bold 24px "PingFang SC", "Microsoft YaHei", sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('🔮 赛博解卦 · 天机报告', cardWidth / 2, padding + 25);

    // 标题下方的华丽渐变质感分割线
    ctx.strokeStyle = 'rgba(212, 175, 55, 0.25)';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(padding, padding + 48);
    ctx.lineTo(cardWidth - padding, padding + 48);
    ctx.stroke();

    // 4. 绘制【推演分析】板块文字
    ctx.textAlign = 'left';
    let y = analysisStartY;

    analysisLines.forEach(line => {
        if (line === '【推演分析】') {
            ctx.fillStyle = '#6366f1'; // 灵动星空霓虹蓝
            ctx.font = 'bold 18px "PingFang SC", "Microsoft YaHei", sans-serif';
            ctx.fillText(line, padding, y);
            y += lineHeight + 6;
        } else {
            ctx.fillStyle = '#e4e4e7'; // 柔和护眼纯白
            ctx.font = '15px "PingFang SC", "Microsoft YaHei", sans-serif';
            ctx.fillText(line, padding, y);
            y += lineHeight;
        }
    });

    // 5. 绘制【断语结果】高亮背景卡片与极客绿文字
    const resultBoxHeight = resultLines.length * lineHeight + 24;
    ctx.fillStyle = 'rgba(16, 185, 129, 0.08)'; // 太极生机翠绿底色
    ctx.fillRect(padding - 12, resultStartY - 20, contentWidth + 24, resultBoxHeight);

    ctx.strokeStyle = 'rgba(16, 185, 129, 0.3)';
    ctx.lineWidth = 1;
    ctx.strokeRect(padding - 12, resultStartY - 20, contentWidth + 24, resultBoxHeight);

    y = resultStartY;
    resultLines.forEach(line => {
        if (line === '【断语结果】') {
            ctx.fillStyle = '#10b981'; // 纯正太极生机绿
            ctx.font = 'bold 18px "PingFang SC", "Microsoft YaHei", sans-serif';
            ctx.fillText(line, padding, y);
            y += lineHeight + 6;
        } else {
            ctx.fillStyle = '#34d399'; // 明亮结论翠绿
            ctx.font = '500 16px "PingFang SC", "Microsoft YaHei", sans-serif';
            ctx.fillText(line, padding, y);
            y += lineHeight;
        }
    });

    // 6. 底部科技感水印
    ctx.fillStyle = '#52525b';
    ctx.font = '12px monospace';
    ctx.textAlign = 'right';
    ctx.fillText('Generated by AI Cyber Divination Assistant', cardWidth - padding, canvas.height - 24);

    // 7. 唤起浏览器无损 PNG 纯净下载
    const dataUrl = canvas.toDataURL('image/png');
    const link = document.createElement('a');
    link.download = `赛博断语报告_${new Date().toISOString().slice(0, 10)}.png`;
    link.href = dataUrl;
    link.click();
};

export const MainPanel = {
    render: (): string => {
        return `<style>${cssContent}</style>\n${htmlContent}`;
    },

    bindEvents: (shadowRoot: ShadowRoot) => {
        const toggleBtn = shadowRoot.getElementById('toggle-btn');
        const mainPanel = shadowRoot.getElementById('main-panel');
        const closeBtn = shadowRoot.getElementById('close-panel-btn');

        const chatHistoryContainer = shadowRoot.getElementById('chat-history');
        const questionInput = shadowRoot.getElementById('question-input') as any;
        const sendBtn = shadowRoot.getElementById('send-btn') as any;

        const extractDataBtn = shadowRoot.getElementById('extract-data-btn') as any;
        const dataStatus = shadowRoot.getElementById('data-status');

        let currentHtmlContent = "";

        // 面板开启与隐藏
        toggleBtn?.addEventListener('click', () => {
            mainPanel!.style.display = 'flex';
            toggleBtn.style.display = 'none';
        });
        closeBtn?.addEventListener('click', () => {
            mainPanel!.style.display = 'none';
            toggleBtn!.style.display = '';
        });

        // 排盘网页数据提取器
        extractDataBtn?.addEventListener('click', () => {
            extractDataBtn.loading = true;
            try {
                currentHtmlContent = PageScraper.extractPaipanData();
                extractDataBtn.variant = "success";
                dataStatus!.style.display = 'inline-block';
                dataStatus!.textContent = `已就绪 (${currentHtmlContent.length}字) ✓`;
            } catch (err) {
                Logger.error("抓取失败", err);
                dataStatus!.style.display = 'inline-block';
                dataStatus!.style.color = 'var(--sl-color-danger-600)';
                dataStatus!.textContent = '抓取失败 ❌';
            } finally {
                extractDataBtn.loading = false;
            }
        });

        const scrollToBottom = () => {
            if (chatHistoryContainer) {
                setTimeout(() => {
                    chatHistoryContainer.scrollTop = chatHistoryContainer.scrollHeight;
                }, 50);
            }
        };

        const appendMessage = (role: 'user' | 'ai', content: string): HTMLElement => {
            const msgDiv = document.createElement('div');
            msgDiv.className = `message ${role}-message`;
            const avatar = role === 'user'
                ? ''
                : `<div class="msg-avatar" style="width: 32px; height: 32px; border-radius: 50%; background-color: var(--sl-color-primary-600); color: white; display: flex; align-items: center; justify-content: center; flex-shrink: 0; box-shadow: var(--sl-shadow-small);">
                       <sl-icon name="cpu" style="font-size: 18px;"></sl-icon>
                   </div>`;

            msgDiv.innerHTML = `
                ${role === 'ai' ? avatar : ''}
                <div class="msg-bubble">${content}</div>
            `;

            chatHistoryContainer!.appendChild(msgDiv);
            scrollToBottom();
            return msgDiv;
        };

        const handleSend = async () => {
            const question = questionInput.value.trim();
            if (!question) return;

            if (!currentHtmlContent) {
                Logger.info('用户未手动抓取，触发自动抓取...');
                currentHtmlContent = PageScraper.extractPaipanData();
                dataStatus!.style.display = 'inline-block';
                dataStatus!.textContent = `自动抓取 (${currentHtmlContent.length}字) ✓`;
            }

            appendMessage('user', question);
            questionInput.value = '';

            sendBtn.disabled = true;
            sendBtn.loading = true;
            questionInput.disabled = true;

            const aiMsgDiv = appendMessage('ai', `<sl-spinner></sl-spinner> <span style="margin-left: 8px;">正在推演天机...</span>`);
            const bubble = aiMsgDiv.querySelector('.msg-bubble') as HTMLElement;

            try {
                const settings = Store.getSettings();
                const res = await AIRequestService.execute(question, currentHtmlContent, currentHistory, settings);

                // 🌟 防御性编程：强制转换为字符串并提供兜底默认值，彻底杜绝 replace is not a function 报错
                const safeAnalysis = String(res.分析过程 || "（AI未返回详细的推演过程，请看最终断语）");
                const safeResult = String(res.结果 || "（AI未能按标准格式返回断语结果）");

                // 🌟 更新 UI 排版：调用安全字符串进行渲染
                bubble.innerHTML = `
                    <div style="display: flex; flex-direction: column; gap: 12px; width: 100%;">
                        <div style="color: var(--sl-color-neutral-700); font-size: 0.95em;">
                            <div style="display: flex; align-items: center; gap: 6px; color: var(--sl-color-primary-600); font-weight: 600; margin-bottom: 8px;">
                                <sl-icon name="compass"></sl-icon>
                                <span>推演分析</span>
                            </div>
                            <div style="padding-left: 10px; border-left: 3px solid var(--sl-color-primary-200); line-height: 1.6; text-align: justify;">
                                ${safeAnalysis.replace(/\n/g, '<br>')}
                            </div>
                        </div>

                        <div style="background-color: var(--sl-color-success-50); border: 1px solid var(--sl-color-success-200); border-radius: 8px; padding: 12px; margin-top: 4px;">
                            <div style="display: flex; align-items: center; gap: 6px; color: var(--sl-color-success-700); font-weight: 600; margin-bottom: 6px;">
                                <sl-icon name="check-circle-fill"></sl-icon>
                                <span>断语结果</span>
                            </div>
                            <div style="color: var(--sl-color-success-900); line-height: 1.6; font-size: 1em; font-weight: 500;">
                                ${safeResult.replace(/\n/g, '<br>')}
                            </div>
                        </div>

                        <div style="display: flex; justify-content: flex-start; gap: 12px; margin-top: 4px; border-top: 1px dashed var(--sl-color-neutral-200); padding-top: 8px;">
                            <sl-button size="small" variant="text" class="copy-report-btn" style="padding: 0; --sl-spacing-x-small: 4px;">
                                <sl-icon name="copy" slot="prefix"></sl-icon>
                                <span class="copy-text">复制报告</span>
                            </sl-button>
                            <sl-button size="small" variant="text" class="export-report-btn" style="padding: 0; --sl-spacing-x-small: 4px;">
                                <sl-icon name="image" slot="prefix"></sl-icon>
                                <span>导出图片</span>
                            </sl-button>
                        </div>
                    </div>
                `;

                const copyBtn = bubble.querySelector('.copy-report-btn') as any;
                const exportBtn = bubble.querySelector('.export-report-btn') as any;

                copyBtn?.addEventListener('click', () => {
                    const plainText = `【推演分析】\n${safeAnalysis}\n\n【断语结果】\n${safeResult}`;
                    navigator.clipboard.writeText(plainText).then(() => {
                        const icon = copyBtn.querySelector('sl-icon');
                        const textSpan = copyBtn.querySelector('.copy-text');
                        if (icon) icon.name = 'check-lg';
                        if (textSpan) textSpan.textContent = '已复制';
                        copyBtn.variant = 'success';

                        setTimeout(() => {
                            if (icon) icon.name = 'copy';
                            if (textSpan) textSpan.textContent = '复制报告';
                            copyBtn.variant = 'text';
                        }, 2000);
                    });
                });

                exportBtn?.addEventListener('click', () => {
                    exportBtn.loading = true;
                    try {
                        // 🌟 使用安全字符串传递给导出图片的函数
                        drawAndExportImage(safeAnalysis, safeResult);
                    } catch (err) {
                        Logger.error("导出分享图失败", err);
                    } finally {
                        exportBtn.loading = false;
                    }
                });

                currentHistory.push({
                    id: Date.now(),
                    question: question,
                    result: res
                });

            } catch (error: any) {
                Logger.error("请求失败", error);
                bubble.innerHTML = `<span style="color: var(--sl-color-danger-600);"><sl-icon name="exclamation-triangle"></sl-icon> 推演失败：<br>${error.message}</span>`;
            } finally {
                sendBtn.disabled = false;
                sendBtn.loading = false;
                questionInput.disabled = false;
                questionInput.focus();
                scrollToBottom();
            }
        };

        sendBtn?.addEventListener('click', handleSend);

        questionInput?.addEventListener('keydown', (e: KeyboardEvent) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                if (!sendBtn.loading) {
                    handleSend();
                }
            }
        });
    }
};